In [17]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:Database_23@localhost:5432/data_pipeline")

ord = pd.read_sql_table("fact_orders", engine)

ord

,order_id,customer_id,order_timestamp,category,product_name,final_amount,shipping_cost,total_revenue,discount_pct,discount_amt,payment_method,order_status,delivery_days,rating,is_returned
0,ORD000431201,CUST0049999,2022-08-11 22:16:00,Electronics,Webcam,1293.0,0.0,1293.0,70,3017.0,UPI,Delivered,5.0,4.0,0
1,ORD000431202,CUST0049995,2022-10-29 20:14:00,Sports,Cycling Gloves,1141.0,0.0,1141.0,30,489.0,Credit Card,Shipped,NaN,NaN,0
2,ORD000431203,CUST0049865,2024-07-21 22:31:00,Fashion,Denim Jeans,8350.5,0.0,8350.5,5,439.5,Credit Card,Delivered,3.0,5.0,0
3,ORD000431204,CUST0049999,2022-12-13 18:10:00,Fashion,Formal Shirt,1608.0,0.0,1608.0,20,402.0,Credit Card,Delivered,4.0,NaN,0
4,ORD000431205,CUST0050000,2023-06-08 20:35:00,Books,Atomic Habits,600.0,0.0,600.0,0,0.0,UPI,Delivered,5.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499995,ORD000431196,CUST0049600,2024-07-27 13:38:00,Home & Kitchen,LED Lamp,825.0,0.0,825.0,25,275.0,Credit Card,Delivered,5.0,3.0,0
1499996,ORD000431197,CUST0049707,2021-01-01 12:10:00,Fashion,Denim Jeans,1458.0,0.0,1458.0,40,972.0,Credit Card,Shipped,NaN,NaN,0
1499997,ORD000431198,CUST0050000,2023-07-24 10:19:00,Home & Kitchen,Wall Clock,6300.0,0.0,6300.0,30,2700.0,Credit Card,Returned,NaN,NaN,1
1499998,ORD000431199,CUST0049998,2021-04-29 08:18:00,Electronics,USB-C Hub,11764.0,0.0,11764.0,15,2076.0,UPI,Delivered,2.0,NaN,0
1499999,ORD000431200,CUST0048877,2021-03-10 18:43:00,Books,Python Crash Course,930.0,0.0,930.0,0,0.0,Credit Card,Delivered,3.0,1.0,0

In [18]:
cust = pd.read_sql_table("dim_customers", engine)
cust

,customer_id,full_name,city,age,gender,customer_segment,registration_date,email_available,phone_available,total_orders,lifetime_spend,avg_order_value,last_order_date,days_since_last_order,churn_status
0,CUST0000001,Vikram Singh,Hyderabad,27,Female,Inactive,2023-05-20,1,1,1,1.336000e+03,1336.00,2024-07-26,157.0,At-Risk
1,CUST0000002,Kevin Young,Delhi,31,Male,Regular,2023-11-05,1,1,0,0.000000e+00,0.00,NaT,NaN,Never Ordered
2,CUST0000003,David Smith,Bangalore,32,Unknown,Inactive,2022-10-18,1,1,0,0.000000e+00,0.00,NaT,NaN,Never Ordered
3,CUST0000004,Fatima Lee,Nagpur,23,Other,Regular,2023-01-29,1,1,0,0.000000e+00,0.00,NaT,NaN,Never Ordered
4,CUST0000005,Fatima Menon,Delhi,44,Male,Premium,2021-05-19,1,1,0,0.000000e+00,0.00,NaT,NaN,Never Ordered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST0049996,Shreya Lee,Mumbai,27,Other,Regular,2020-12-26,1,1,48787,1.439630e+08,2950.85,2024-12-30,0.0,Active
49996,CUST0049997,Mia Sharma,Pune,31,Female,Premium,2023-05-13,1,1,65248,1.938326e+08,2970.71,2024-12-30,0.0,Active
49997,CUST0049998,Arjun Williams,Pune,44,Female,Inactive,2021-06-21,1,1,94682,2.768908e+08,2924.43,2024-12-30,0.0,Active
49998,CUST0049999,Kavya Sharma,Surat,40,Male,Premium,2023-02-24,1,1,160003,4.712692e+08,2945.38,2024-12-30,0.0,Active
49999,CUST0050000,Maria Thompson,Delhi,32,Male,Regular,2022-05-18,0,1,394195,1.157758e+09,2937.02,2024-12-30,0.0,Active

In [21]:
df = pd.merge(ord, cust, on="customer_id", how="inner")

df

,order_id,customer_id,order_timestamp,category,product_name,final_amount,shipping_cost,total_revenue,discount_pct,discount_amt,...,customer_segment,registration_date,email_available,phone_available,total_orders,lifetime_spend,avg_order_value,last_order_date,days_since_last_order,churn_status
0,ORD000431201,CUST0049999,2022-08-11 22:16:00,Electronics,Webcam,1293.0,0.0,1293.0,70,3017.0,...,Premium,2023-02-24,1,1,160003,4.712692e+08,2945.38,2024-12-30,0.0,Active
1,ORD000431202,CUST0049995,2022-10-29 20:14:00,Sports,Cycling Gloves,1141.0,0.0,1141.0,30,489.0,...,Inactive,2023-03-13,1,1,38570,1.121693e+08,2908.20,2024-12-30,0.0,Active
2,ORD000431203,CUST0049865,2024-07-21 22:31:00,Fashion,Denim Jeans,8350.5,0.0,8350.5,5,439.5,...,Regular,2021-07-31,1,1,657,2.047984e+06,3117.18,2024-12-29,1.0,Active
3,ORD000431204,CUST0049999,2022-12-13 18:10:00,Fashion,Formal Shirt,1608.0,0.0,1608.0,20,402.0,...,Premium,2023-02-24,1,1,160003,4.712692e+08,2945.38,2024-12-30,0.0,Active
4,ORD000431205,CUST0050000,2023-06-08 20:35:00,Books,Atomic Habits,600.0,0.0,600.0,0,0.0,...,Regular,2022-05-18,0,1,394195,1.157758e+09,2937.02,2024-12-30,0.0,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499995,ORD000431196,CUST0049600,2024-07-27 13:38:00,Home & Kitchen,LED Lamp,825.0,0.0,825.0,25,275.0,...,Regular,2022-02-23,1,1,173,5.609400e+05,3242.43,2024-12-22,8.0,Active
1499996,ORD000431197,CUST0049707,2021-01-01 12:10:00,Fashion,Denim Jeans,1458.0,0.0,1458.0,40,972.0,...,Regular,2023-05-21,1,1,241,7.309285e+05,3032.90,2024-12-24,6.0,Active
1499997,ORD000431198,CUST0050000,2023-07-24 10:19:00,Home & Kitchen,Wall Clock,6300.0,0.0,6300.0,30,2700.0,...,Regular,2022-05-18,0,1,394195,1.157758e+09,2937.02,2024-12-30,0.0,Active
1499998,ORD000431199,CUST0049998,2021-04-29 08:18:00,Electronics,USB-C Hub,11764.0,0.0,11764.0,15,2076.0,...,Inactive,2021-06-21,1,1,94682,2.768908e+08,2924.43,2024-12-30,0.0,Active
1499999,ORD000431200,CUST0048877,2021-03-10 18:43:00,Books,Python Crash Course,930.0,0.0,930.0,0,0.0,...,Regular,2022-12-31,1,1,52,1.090850e+05,2097.79,2024-08-09,143.0,At-Risk

In [22]:
query = "Select * from fact_orders inner join dim_customers using (customer_id)"

table = pd.read_sql_query(query, engine)

table

,customer_id,order_id,order_timestamp,category,product_name,final_amount,shipping_cost,total_revenue,discount_pct,discount_amt,...,customer_segment,registration_date,email_available,phone_available,total_orders,lifetime_spend,avg_order_value,last_order_date,days_since_last_order,churn_status
0,CUST0049999,ORD000431201,2022-08-11 22:16:00,Electronics,Webcam,1293.0,0.0,1293.0,70,3017.0,...,Premium,2023-02-24,1,1,160003,4.712692e+08,2945.38,2024-12-30,0,Active
1,CUST0049995,ORD000431202,2022-10-29 20:14:00,Sports,Cycling Gloves,1141.0,0.0,1141.0,30,489.0,...,Inactive,2023-03-13,1,1,38570,1.121693e+08,2908.20,2024-12-30,0,Active
2,CUST0049865,ORD000431203,2024-07-21 22:31:00,Fashion,Denim Jeans,8350.5,0.0,8350.5,5,439.5,...,Regular,2021-07-31,1,1,657,2.047984e+06,3117.18,2024-12-29,1,Active
3,CUST0049999,ORD000431204,2022-12-13 18:10:00,Fashion,Formal Shirt,1608.0,0.0,1608.0,20,402.0,...,Premium,2023-02-24,1,1,160003,4.712692e+08,2945.38,2024-12-30,0,Active
4,CUST0050000,ORD000431205,2023-06-08 20:35:00,Books,Atomic Habits,600.0,0.0,600.0,0,0.0,...,Regular,2022-05-18,0,1,394195,1.157758e+09,2937.02,2024-12-30,0,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499995,CUST0048755,ORD000431152,2024-04-20 15:25:00,Grocery,Protein Bar,621.0,0.0,621.0,10,69.0,...,Regular,2021-05-01,1,1,40,1.255345e+05,3138.36,2024-11-01,59,Active
1499996,CUST0042459,ORD000431170,2020-07-26 09:03:00,Electronics,Bluetooth Speaker,2240.0,0.0,2240.0,30,960.0,...,Regular,2023-11-04,1,1,4,5.260000e+03,1315.00,2022-10-19,803,Churned
1499997,CUST0049507,ORD000431187,2021-11-30 10:52:00,Electronics,Laptop Stand,2888.0,0.0,2888.0,20,722.0,...,Regular,2022-08-17,1,1,126,3.069180e+05,2435.86,2024-12-09,21,Active
1499998,CUST0049697,ORD000431191,2021-12-13 12:40:00,Home & Kitchen,Water Bottle,2100.0,0.0,2100.0,30,900.0,...,Regular,2022-12-30,1,1,222,6.846115e+05,3083.84,2024-12-01,29,Active
1499999,CUST0049600,ORD000431196,2024-07-27 13:38:00,Home & Kitchen,LED Lamp,825.0,0.0,825.0,25,275.0,...,Regular,2022-02-23,1,1,173,5.609400e+05,3242.43,2024-12-22,8,Active

In [ ]:
path =